/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "platform/android/jni/JniHelper.h"
#include <android/log.h>
#include "cocos2d.h"
#include <string>
#include <vector>
#include <map>
#include "Cocos2dx/Common/CCUMPushSDK.h"
/* Header for class com_umeng_social_CCUMSocialController */
USING_NS_CC;
using namespace std;


#ifndef _Included_com_umeng_push_CCUMPushController
#define _Included_com_umeng_push_CCUMPushController
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_umeng_push_CCUMPushController_TagsCallBack(
		JNIEnv *, jclass,jint, jobjectArray);


JNIEXPORT void JNICALL Java_com_umeng_push_CCUMPushController_AliasCallback(
		JNIEnv *, jclass, jint );

JNIEXPORT void JNICALL Java_com_umeng_push_CCUMPushController_RemainCallback(
		JNIEnv *, jclass, jint, jint );


   void addTags(const char *tags,  PushRemainTagsCallBack callback);
    void deleteTags(const char *tags,  PushRemainTagsCallBack callback);
    void getTags(PushGetTagsCallBack callback);
    void addAlias(const char *name, const char *type, PushAliasCallBack callback);
    void setAlias(const char *name, const char *type, PushAliasCallBack callback);
    void removeAlias(const char *name, const char *type, PushAliasCallBack callback);
bool getPushMethod(JniMethodInfo &mi, const char *methodName, const char *sig);

/*
 * 释放方法对象
 * @param mi 要释放的方法对象
 */
void releasePushMethod(JniMethodInfo &mi);



#ifdef __cplusplus
}
#endif
#endif
